INDICATORS_TO_IDS = {
    "Number of Employees": "0-3",
    "Founding Year": "0-5",
    "Headquarter Location": "0-6",
    "Sector Classification": "0-73",
    "Ticker": "0-71",
    "Last Closing Price": "0-31",
    "Market Capitalisation": "4-11",
    "Common Shares Outstanding": "0-64",
    "Preferred Shares Outstanding": "0-65",
    "Average Shares Outstanding, basic": "0-66",
    "Average Shares Outstanding, diluted": "0-67",
    "Revenues": "1-1",
    "Cost of Goods Sold": "1-2",
    "Gross Profit": "1-4",
    "Operating Expenses": "1-11",
    "Selling, General and Administrative": "1-12",
    "Research & Development Expenses": "1-15",
    "Operating Income (EBIT)": "1-19",
    "EBITDA": "4-10",
    "Interest Expense, net": "1-21",
    "Pretax Income (adjusted)": "1-28",
    "Pretax Income": "1-43",
    "Income Taxes": "1-44",
    "Income from Continuing Operations": "1-49",
    "Net Income (common shareholders)": "1-58",
    "Cash and Cash-equivalents": "2-1",
    "Receivables, net": "2-5",
    "Total Current Assets": "2-21",
    "Property, Plant and Equipment, net": "2-22",
    "Total Assets": "2-41",
    "Accounts payable": "2-43",
    "Current Debt": "2-47",
    "Total Current Liabilities": "2-57",
    "Non-current Debt": "2-58",
    "Total Debt": "4-6",
    "Total Liabilities": "2-73",
    "Preferred Equity": "2-74",
    "Common Stock": "2-76",
    "Equity before minorities": "2-82",
    "Minority Interest": "2-83",
    "Total Equity": "2-84",
    "Depreciation & Amortisation": "3-2",
    "Change in Working Capital": "3-7",
    "Operating Cash Flow": "3-13",
    "Net Change in PP&E & Intangibles": "3-14",
    "Investing Cash Flow": "3-31",
    "Dividends paid": "3-32",
    "Financing Cash Flow": "3-43",
    "Net Change in Cash": "3-46",
    "Free Cash Flow": "4-25",
    "Gross Margin": "4-0",
    "Operating Margin": "4-1",
    "Net Profit Margin": "4-2",
    "Return on Equity": "4-7",
    "Return on Assets": "4-9",
    "Free Cash Flow to Net Income": "4-28",
    "Current Ratio": "4-3",
    "Liabilities to Equity Ratio": "4-4",
    "Debt to Assets Ratio": "4-5",
    "Earnings per Share, Basic": "4-12",
    "Earnings per Share, Diluted": "4-13",
    "Sales per Share": "4-17",
    "Book Value per Share": "4-18",
    "Free Cash Flow per Share": "4-26",
    "Dividends per Share": "4-29",
    "Price to Earnings Ratio": "4-14",
    "Price to Sales Ratio": "4-15",
    "Price to Book Value": "4-16",
    "Price to Free Cash Flow": "4-27",
    "Enterprise Value": "4-20",
    "EV/EBITDA": "4-21",
    "EV/Sales": "4-22",
    "EV/FCF": "4-31",
    "Book to Market Value": "4-23",
    "Operating Income/EV": "4-24",
    "Pietroski F-Score": "4-30"
}